kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: "{{meta.name}}"
  name: "{{meta.name}}"
  namespace: "{{ meta.namespace }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{meta.name}}"
  template:
    metadata:
      labels:
        app: "{{meta.name}}"
    spec:
      containers:
        - name: "nginx"
          image: "{{nginx_image}}"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: "{{meta.name}}"
              mountPath: /opt/app-root/src
      volumes:
        - name: "{{meta.name}}"
          configMap:
            name: "{{meta.name}}"
