apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: "{{meta.name}}"
  namespace: "{{meta.namespace}}"
spec:
  termination: edge
  port:
    targetPort: 8080
  to:
    kind: Service
    name: "{{meta.name}}"
    weight: 100