- name: Create website configmap
  k8s:
    state: "{{ state }}"
    definition: "{{ lookup('template', 'templates/cm.yaml') }}"

- name: Create Nginx instance
  k8s:
    state: "{{ state }}"
    definition: "{{ lookup('template', 'templates/nginx-deployment.yaml') }}"

- name: Create service for Nginx instance
  k8s:
    state: "{{ state }}"
    definition: "{{ lookup('template', 'templates/service.yaml') }}"

- name: Create route for Nginx instance
  k8s:
    state: "{{ state }}"
    definition: "{{ lookup('template', 'templates/route.yaml') }}"
